export function getRandomCityState(cityStateArray) {
  const randomIndex = Math.floor(Math.random() * cityStateArray.length);
  return cityStateArray[randomIndex];
}

const cityStateArray = [
  "Salem, NY",
  "Marina del Sol, CA",
  "Haven City, IL",
  "Evergreen, TX",
  "Golden Valley, AZ",
  "Harmonyville, PA",
  "Cascade Falls, TX",
  "Oceanview, CA",
  "Silverton, TX",
  "Maplewood, CA",
  "Avalon, TX",
  "Cypress Creek, FL",
  "Starfield, TX",
  "Lakeside, OH",
  "Emerald Bay, CA",
  "Whispering Pines, NC",
  "Harmony Hills, IN",
  "Misty Harbor, WA",
  "Rocky Ridge, CO",
  "Union City, D.C.",
  "Meadowville, MA",
  "Sunset Hills, TX",
  "Hawthorne, MI",
  "Hillcrest, TN",
  "Tranquil Springs, TN",
  "Pinegrove, OR",
  "Sunset City, OK",
  "Desert Oasis, NV",
  "Riverdale, KY",
  "Harborview, MD",
  "Northbrook, WI",
  "Sierra Vista, NM",
  "Roseville, AZ",
  "Amberwood, CA",
  "Cascade Springs, CA",
  "Mesa Verde, AZ",
  "Prairieville, MO",
  "Bayview, GA",
  "Rocky Mountain, CO",
  "Seaside, FL",
  "Woodland, NC",
  "Willow Creek, NE",
  "Oceanfront, CA",
  "Coral Bay, VA",
  "Oakridge, CA",
  "Northfield, MN",
  "Echo Springs, OK",
  "Stonebridge, TX",
  "Harbor Bay, FL",
  "Crescent City, LA",
];

export const randomCityState = getRandomCityState(cityStateArray);
